{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: google-api-python-client in /home/alllhvhla/.local/lib/python3.9/site-packages (2.49.0)\n",
      "Requirement already satisfied: httplib2<1dev,>=0.15.0 in /usr/lib/python3/dist-packages (from google-api-python-client) (0.18.1)\n",
      "Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-python-client) (2.8.0)\n",
      "Requirement already satisfied: uritemplate<5,>=3.0.1 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-python-client) (4.1.1)\n",
      "Requirement already satisfied: google-auth-httplib2>=0.1.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-python-client) (0.1.0)\n",
      "Requirement already satisfied: google-auth<3.0.0dev,>=1.16.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-python-client) (1.35.0)\n",
      "Requirement already satisfied: protobuf>=3.12.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (4.21.0)\n",
      "Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (2.26.0)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.52.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (1.56.1)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (4.7.2)\n",
      "Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (4.2.4)\n",
      "Requirement already satisfied: setuptools>=40.3.0 in /usr/lib/python3/dist-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (52.0.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (0.2.8)\n",
      "Requirement already satisfied: six>=1.9.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (1.12.0)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/alllhvhla/.local/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (0.4.8)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (2.8)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (2.0.9)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (1.26.7)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (2020.6.20)\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: google-auth in /home/alllhvhla/.local/lib/python3.9/site-packages (1.35.0)\n",
      "Collecting google-auth\n",
      "  Using cached google_auth-2.6.6-py2.py3-none-any.whl (156 kB)\n",
      "Requirement already satisfied: google-auth-oauthlib in /home/alllhvhla/.local/lib/python3.9/site-packages (0.4.6)\n",
      "Collecting google-auth-oauthlib\n",
      "  Downloading google_auth_oauthlib-0.5.1-py2.py3-none-any.whl (19 kB)\n",
      "Requirement already satisfied: google-auth-httplib2 in /home/alllhvhla/.local/lib/python3.9/site-packages (0.1.0)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth) (4.2.4)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth) (4.7.2)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth) (0.2.8)\n",
      "Requirement already satisfied: six>=1.9.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth) (1.12.0)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth-oauthlib) (1.3.0)\n",
      "Requirement already satisfied: httplib2>=0.15.0 in /usr/lib/python3/dist-packages (from google-auth-httplib2) (0.18.1)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/alllhvhla/.local/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth) (0.4.8)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (3.1.0)\n",
      "Requirement already satisfied: requests>=2.0.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib) (2.26.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (2.8)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (2020.6.20)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (2.0.9)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib) (1.26.7)\n",
      "Installing collected packages: google-auth, google-auth-oauthlib\n",
      "  Attempting uninstall: google-auth\n",
      "    Found existing installation: google-auth 1.35.0\n",
      "    Uninstalling google-auth-1.35.0:\n",
      "      Successfully uninstalled google-auth-1.35.0\n",
      "  Attempting uninstall: google-auth-oauthlib\n",
      "    Found existing installation: google-auth-oauthlib 0.4.6\n",
      "    Uninstalling google-auth-oauthlib-0.4.6:\n",
      "      Successfully uninstalled google-auth-oauthlib-0.4.6\n",
      "\u001b[33m  WARNING: The script google-oauthlib-tool is installed in '/home/alllhvhla/.local/bin' which is not on PATH.\n",
      "  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "tensorboard 2.7.0 requires google-auth-oauthlib<0.5,>=0.4.1, but you have google-auth-oauthlib 0.5.1 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed google-auth-2.6.6 google-auth-oauthlib-0.5.1\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: flask in /home/alllhvhla/.local/lib/python3.9/site-packages (2.1.2)\n",
      "Requirement already satisfied: importlib-metadata>=3.6.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from flask) (4.8.2)\n",
      "Requirement already satisfied: Werkzeug>=2.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from flask) (2.0.2)\n",
      "Requirement already satisfied: Jinja2>=3.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from flask) (3.1.2)\n",
      "Requirement already satisfied: click>=8.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from flask) (8.1.3)\n",
      "Requirement already satisfied: itsdangerous>=2.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from flask) (2.1.2)\n",
      "Requirement already satisfied: zipp>=0.5 in /usr/lib/python3/dist-packages (from importlib-metadata>=3.6.0->flask) (1.0.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from Jinja2>=3.0->flask) (2.1.1)\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: requests in /home/alllhvhla/.local/lib/python3.9/site-packages (2.26.0)\n",
      "Collecting requests\n",
      "  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests) (2.0.9)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests) (2.8)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests) (1.26.7)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests) (2020.6.20)\n",
      "Installing collected packages: requests\n",
      "  Attempting uninstall: requests\n",
      "    Found existing installation: requests 2.26.0\n",
      "    Uninstalling requests-2.26.0:\n",
      "      Successfully uninstalled requests-2.26.0\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "tensorboard 2.7.0 requires google-auth-oauthlib<0.5,>=0.4.1, but you have google-auth-oauthlib 0.5.1 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed requests-2.27.1\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade google-api-python-client\n",
    "!pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2\n",
    "!pip install --upgrade flask\n",
    "!pip install --upgrade requests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: The index url \"gnore-installed\" seems invalid, please provide a scheme.\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: gnore-installed\n",
      "Requirement already satisfied: google-api-python-client in /home/alllhvhla/.local/lib/python3.9/site-packages (2.49.0)\n",
      "\u001b[33mWARNING: Location 'gnore-installed/google-api-python-client/' is ignored: it is either a non-existing path or lacks a specific scheme.\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: google-auth<3.0.0dev,>=1.16.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-python-client) (2.6.6)\n",
      "Requirement already satisfied: google-auth-httplib2>=0.1.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-python-client) (0.1.0)\n",
      "Requirement already satisfied: uritemplate<5,>=3.0.1 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-python-client) (4.1.1)\n",
      "Requirement already satisfied: httplib2<1dev,>=0.15.0 in /usr/lib/python3/dist-packages (from google-api-python-client) (0.18.1)\n",
      "Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-python-client) (2.8.0)\n",
      "Requirement already satisfied: protobuf>=3.12.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (4.21.0)\n",
      "Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (2.27.1)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.52.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (1.56.1)\n",
      "Requirement already satisfied: six>=1.9.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (1.12.0)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (4.2.4)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (0.2.8)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (4.7.2)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/alllhvhla/.local/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (0.4.8)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (2.0.9)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (2020.6.20)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (2.8)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (1.26.7)\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: The index url \"gnore-installed\" seems invalid, please provide a scheme.\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: gnore-installed\n",
      "Requirement already satisfied: google-cloud in /home/alllhvhla/.local/lib/python3.9/site-packages (0.34.0)\n",
      "\u001b[33mWARNING: Location 'gnore-installed/google-cloud/' is ignored: it is either a non-existing path or lacks a specific scheme.\u001b[0m\u001b[33m\n",
      "\u001b[0mDefaulting to user installation because normal site-packages is not writeable\n",
      "\u001b[33mWARNING: The index url \"gnore-installed\" seems invalid, please provide a scheme.\u001b[0m\u001b[33m\n",
      "\u001b[0mLooking in indexes: gnore-installed\n",
      "Requirement already satisfied: google-cloud-vision in /home/alllhvhla/.local/lib/python3.9/site-packages (2.7.2)\n",
      "\u001b[33mWARNING: Location 'gnore-installed/google-cloud-vision/' is ignored: it is either a non-existing path or lacks a specific scheme.\u001b[0m\u001b[33m\n",
      "\u001b[0mRequirement already satisfied: google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-cloud-vision) (2.8.0)\n",
      "Requirement already satisfied: proto-plus>=1.15.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-cloud-vision) (1.20.4)\n",
      "Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (2.27.1)\n",
      "Requirement already satisfied: protobuf>=3.12.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (4.21.0)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.52.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (1.56.1)\n",
      "Requirement already satisfied: google-auth<3.0dev,>=1.25.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (2.6.6)\n",
      "Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (1.46.3)\n",
      "Requirement already satisfied: grpcio-status<2.0dev,>=1.33.2 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (1.46.3)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (4.7.2)\n",
      "Requirement already satisfied: six>=1.9.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (1.12.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (0.2.8)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (4.2.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (2020.6.20)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (1.26.7)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (2.8)\n",
      "Requirement already satisfied: charset-normalizer~=2.0.0 in /home/alllhvhla/.local/lib/python3.9/site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (2.0.9)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/alllhvhla/.local/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=1.25.0->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-vision) (0.4.8)\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade -ignore-installed google-api-python-client\n",
    "!pip install --upgrade -ignore-installed google-cloud\n",
    "!pip install --upgrade -ignore-installed google-cloud-vision"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "cannot import name 'dialogflow' from 'google.cloud' (unknown location)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_7530/1312347987.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     29\u001b[0m         )\n\u001b[1;32m     30\u001b[0m         \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Fulfillment text: {}\\n\"\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mformat\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mresponse\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mquery_result\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfulfillment_text\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 31\u001b[0;31m \u001b[0mdetect_intent_texts\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"who-am-i-afhy\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"1\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"너는 고양이지\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'ko-KR'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/tmp/ipykernel_7530/1312347987.py\u001b[0m in \u001b[0;36mdetect_intent_texts\u001b[0;34m(project_id, session_id, texts, language_code)\u001b[0m\n\u001b[1;32m      4\u001b[0m     \u001b[0mUsing\u001b[0m \u001b[0mthe\u001b[0m \u001b[0msame\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m`\u001b[0m\u001b[0msession_id\u001b[0m\u001b[0;31m`\u001b[0m \u001b[0mbetween\u001b[0m \u001b[0mrequests\u001b[0m \u001b[0mallows\u001b[0m \u001b[0mcontinuation\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     of the conversation.\"\"\"\n\u001b[0;32m----> 6\u001b[0;31m     \u001b[0;32mfrom\u001b[0m \u001b[0mgoogle\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcloud\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mdialogflow\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      7\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m     \u001b[0msession_client\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdialogflow\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSessionsClient\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mImportError\u001b[0m: cannot import name 'dialogflow' from 'google.cloud' (unknown location)"
     ]
    }
   ],
   "source": [
    "def detect_intent_texts(project_id, session_id, texts, language_code):\n",
    "    \"\"\"Returns the result of detect intent with texts as inputs.\n",
    "\n",
    "    Using the same `session_id` between requests allows continuation\n",
    "    of the conversation.\"\"\"\n",
    "    from google.cloud import dialogflow\n",
    "\n",
    "    session_client = dialogflow.SessionsClient()\n",
    "\n",
    "    session = session_client.session_path(project_id, session_id)\n",
    "    print(\"Session path: {}\\n\".format(session))\n",
    "\n",
    "    for text in texts:\n",
    "        text_input = dialogflow.TextInput(text=text, language_code=language_code)\n",
    "\n",
    "        query_input = dialogflow.QueryInput(text=text_input)\n",
    "\n",
    "        response = session_client.detect_intent(\n",
    "            request={\"session\": session, \"query_input\": query_input}\n",
    "        )\n",
    "\n",
    "        print(\"=\" * 20)\n",
    "        print(\"Query text: {}\".format(response.query_result.query_text))\n",
    "        print(\n",
    "            \"Detected intent: {} (confidence: {})\\n\".format(\n",
    "                response.query_result.intent.display_name,\n",
    "                response.query_result.intent_detection_confidence,\n",
    "            )\n",
    "        )\n",
    "        print(\"Fulfillment text: {}\\n\".format(response.query_result.fulfillment_text))\n",
    "detect_intent_texts(\"who-am-i-afhy\", \"1\", \"너는 고양이지\", 'ko-KR')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import google.oauth2.credentials\n",
    "import google_auth_oauthlib.flow\n",
    "\n",
    "# Use the client_secret.json file to identify the application requesting\n",
    "# authorization. The client ID (from that file) and access scopes are required.\n",
    "flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(\n",
    "    './client_secret.json',\n",
    "    scopes=['https://www.googleapis.com/auth/drive.metadata.readonly'])\n",
    "\n",
    "# Indicate where the API server will redirect the user after the user completes\n",
    "# the authorization flow. The redirect URI is required. The value must exactly\n",
    "# match one of the authorized redirect URIs for the OAuth 2.0 client, which you\n",
    "# configured in the API Console. If this value doesn't match an authorized URI,\n",
    "# you will get a 'redirect_uri_mismatch' error.\n",
    "flow.redirect_uri = 'https://www.example.com/oauth2callback'\n",
    "\n",
    "# Generate URL for request to Google's OAuth 2.0 server.\n",
    "# Use kwargs to set optional request parameters.\n",
    "authorization_url, state = flow.authorization_url(\n",
    "    # Enable offline access so that you can refresh an access token without\n",
    "    # re-prompting the user for permission. Recommended for web server apps.\n",
    "    access_type='offline',\n",
    "    # Enable incremental authorization. Recommended as a best practice.\n",
    "    include_granted_scopes='true')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "import flask"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=292641359392-p3sfecde49h5gfonfp42en9fabi4j7fl.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fwww.example.com%2Foauth2callback&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.metadata.readonly&state=L5xJQUJUvkqutmvy9U2cKEYOXERTV7&access_type=offline&include_granted_scopes=true\n"
     ]
    }
   ],
   "source": [
    "flask.redirect(authorization_url)\n",
    "print(authorization_url)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "ename": "RuntimeError",
     "evalue": "Working outside of request context.\n\nThis typically means that you attempted to use functionality that needed\nan active HTTP request.  Consult the documentation on testing for\ninformation about how to avoid this problem.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_40711/4283395061.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mstate\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mflask\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msession\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'state'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(\n\u001b[1;32m      3\u001b[0m     \u001b[0;34m'client_secret.json'\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m     \u001b[0mscopes\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'https://www.googleapis.com/auth/drive.metadata.readonly'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     state=state)\n",
      "\u001b[0;32m~/.local/lib/python3.9/site-packages/werkzeug/local.py\u001b[0m in \u001b[0;36m__get__\u001b[0;34m(self, instance, owner)\u001b[0m\n\u001b[1;32m    430\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    431\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 432\u001b[0;31m             \u001b[0mobj\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0minstance\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_get_current_object\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    433\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    434\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfallback\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.9/site-packages/werkzeug/local.py\u001b[0m in \u001b[0;36m_get_current_object\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    552\u001b[0m         \"\"\"\n\u001b[1;32m    553\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mhasattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__local\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"__release_local__\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# type: ignore\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 554\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__local\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m  \u001b[0;31m# type: ignore\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    555\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    556\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.9/site-packages/flask/globals.py\u001b[0m in \u001b[0;36m_lookup_req_object\u001b[0;34m(name)\u001b[0m\n\u001b[1;32m     31\u001b[0m     \u001b[0mtop\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_request_ctx_stack\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtop\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     32\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mtop\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 33\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_request_ctx_err_msg\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     34\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtop\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     35\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mRuntimeError\u001b[0m: Working outside of request context.\n\nThis typically means that you attempted to use functionality that needed\nan active HTTP request.  Consult the documentation on testing for\ninformation about how to avoid this problem."
     ]
    }
   ],
   "source": [
    "state = flask.session['state']\n",
    "flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(\n",
    "    'client_secret.json',\n",
    "    scopes=['https://www.googleapis.com/auth/drive.metadata.readonly'],\n",
    "    state=state)\n",
    "flow.redirect_uri = flask.url_for('oauth2callback', _external=True)\n",
    "\n",
    "authorization_response = flask.request.url\n",
    "flow.fetch_token(authorization_response=authorization_response)\n",
    "\n",
    "# Store the credentials in the session.\n",
    "# ACTION ITEM for developers:\n",
    "#     Store user's access and refresh tokens in your data store if\n",
    "#     incorporating this code into your real app.\n",
    "credentials = flow.credentials\n",
    "flask.session['credentials'] = {\n",
    "    'token': credentials.token,\n",
    "    'refresh_token': credentials.refresh_token,\n",
    "    'token_uri': credentials.token_uri,\n",
    "    'client_id': credentials.client_id,\n",
    "    'client_secret': credentials.client_secret,\n",
    "    'scopes': credentials.scopes}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app '__main__' (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    }
   ],
   "source": [
    "# -*- coding: utf-8 -*-\n",
    "\n",
    "import os\n",
    "import flask\n",
    "import requests\n",
    "\n",
    "import google.oauth2.credentials\n",
    "import google_auth_oauthlib.flow\n",
    "import googleapiclient.discovery\n",
    "\n",
    "# This variable specifies the name of a file that contains the OAuth 2.0\n",
    "# information for this application, including its client_id and client_secret.\n",
    "CLIENT_SECRETS_FILE = \"client_secret.json\"\n",
    "\n",
    "# This OAuth 2.0 access scope allows for full read/write access to the\n",
    "# authenticated user's account and requires requests to use an SSL connection.\n",
    "SCOPES = ['https://www.googleapis.com/auth/drive.metadata.readonly']\n",
    "API_SERVICE_NAME = 'drive'\n",
    "API_VERSION = 'v2'\n",
    "\n",
    "app = flask.Flask(__name__)\n",
    "# Note: A secret key is included in the sample so that it works.\n",
    "# If you use this code in your application, replace this with a truly secret\n",
    "# key. See https://flask.palletsprojects.com/quickstart/#sessions.\n",
    "# app.secret_key = 'REPLACE ME - this value is here as a placeholder.'\n",
    "\n",
    "\n",
    "@app.route('/')\n",
    "def index():\n",
    "  return print_index_table()\n",
    "\n",
    "\n",
    "@app.route('/test')\n",
    "def test_api_request():\n",
    "  if 'credentials' not in flask.session:\n",
    "    return flask.redirect('authorize')\n",
    "\n",
    "  # Load credentials from the session.\n",
    "  credentials = google.oauth2.credentials.Credentials(\n",
    "      **flask.session['credentials'])\n",
    "\n",
    "  drive = googleapiclient.discovery.build(\n",
    "      API_SERVICE_NAME, API_VERSION, credentials=credentials)\n",
    "\n",
    "  files = drive.files().list().execute()\n",
    "\n",
    "  # Save credentials back to session in case access token was refreshed.\n",
    "  # ACTION ITEM: In a production app, you likely want to save these\n",
    "  #              credentials in a persistent database instead.\n",
    "  flask.session['credentials'] = credentials_to_dict(credentials)\n",
    "\n",
    "  return flask.jsonify(**files)\n",
    "\n",
    "\n",
    "@app.route('/authorize')\n",
    "def authorize():\n",
    "  # Create flow instance to manage the OAuth 2.0 Authorization Grant Flow steps.\n",
    "  flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(\n",
    "      CLIENT_SECRETS_FILE, scopes=SCOPES)\n",
    "\n",
    "  # The URI created here must exactly match one of the authorized redirect URIs\n",
    "  # for the OAuth 2.0 client, which you configured in the API Console. If this\n",
    "  # value doesn't match an authorized URI, you will get a 'redirect_uri_mismatch'\n",
    "  # error.\n",
    "  flow.redirect_uri = flask.url_for('oauth2callback', _external=True)\n",
    "\n",
    "  authorization_url, state = flow.authorization_url(\n",
    "      # Enable offline access so that you can refresh an access token without\n",
    "      # re-prompting the user for permission. Recommended for web server apps.\n",
    "      access_type='offline',\n",
    "      # Enable incremental authorization. Recommended as a best practice.\n",
    "      include_granted_scopes='true')\n",
    "\n",
    "  # Store the state so the callback can verify the auth server response.\n",
    "  flask.session['state'] = state\n",
    "\n",
    "  return flask.redirect(authorization_url)\n",
    "\n",
    "\n",
    "@app.route('/oauth2callback')\n",
    "def oauth2callback():\n",
    "  # Specify the state when creating the flow in the callback so that it can\n",
    "  # verified in the authorization server response.\n",
    "  state = flask.session['state']\n",
    "\n",
    "  flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(\n",
    "      CLIENT_SECRETS_FILE, scopes=SCOPES, state=state)\n",
    "  flow.redirect_uri = flask.url_for('oauth2callback', _external=True)\n",
    "\n",
    "  # Use the authorization server's response to fetch the OAuth 2.0 tokens.\n",
    "  authorization_response = flask.request.url\n",
    "  flow.fetch_token(authorization_response=authorization_response)\n",
    "\n",
    "  # Store credentials in the session.\n",
    "  # ACTION ITEM: In a production app, you likely want to save these\n",
    "  #              credentials in a persistent database instead.\n",
    "  credentials = flow.credentials\n",
    "  flask.session['credentials'] = credentials_to_dict(credentials)\n",
    "\n",
    "  return flask.redirect(flask.url_for('test_api_request'))\n",
    "\n",
    "\n",
    "@app.route('/revoke')\n",
    "def revoke():\n",
    "  if 'credentials' not in flask.session:\n",
    "    return ('You need to <a href=\"/authorize\">authorize</a> before ' +\n",
    "            'testing the code to revoke credentials.')\n",
    "\n",
    "  credentials = google.oauth2.credentials.Credentials(\n",
    "    **flask.session['credentials'])\n",
    "\n",
    "  revoke = requests.post('https://oauth2.googleapis.com/revoke',\n",
    "      params={'token': credentials.token},\n",
    "      headers = {'content-type': 'application/x-www-form-urlencoded'})\n",
    "\n",
    "  status_code = getattr(revoke, 'status_code')\n",
    "  if status_code == 200:\n",
    "    return('Credentials successfully revoked.' + print_index_table())\n",
    "  else:\n",
    "    return('An error occurred.' + print_index_table())\n",
    "\n",
    "\n",
    "@app.route('/clear')\n",
    "def clear_credentials():\n",
    "  if 'credentials' in flask.session:\n",
    "    del flask.session['credentials']\n",
    "  return ('Credentials have been cleared.<br><br>' +\n",
    "          print_index_table())\n",
    "\n",
    "\n",
    "def credentials_to_dict(credentials):\n",
    "  return {'token': credentials.token,\n",
    "          'refresh_token': credentials.refresh_token,\n",
    "          'token_uri': credentials.token_uri,\n",
    "          'client_id': credentials.client_id,\n",
    "          'client_secret': credentials.client_secret,\n",
    "          'scopes': credentials.scopes}\n",
    "\n",
    "def print_index_table():\n",
    "  return ('<table>' +\n",
    "          '<tr><td><a href=\"/test\">Test an API request</a></td>' +\n",
    "          '<td>Submit an API request and see a formatted JSON response. ' +\n",
    "          '    Go through the authorization flow if there are no stored ' +\n",
    "          '    credentials for the user.</td></tr>' +\n",
    "          '<tr><td><a href=\"/authorize\">Test the auth flow directly</a></td>' +\n",
    "          '<td>Go directly to the authorization flow. If there are stored ' +\n",
    "          '    credentials, you still might not be prompted to reauthorize ' +\n",
    "          '    the application.</td></tr>' +\n",
    "          '<tr><td><a href=\"/revoke\">Revoke current credentials</a></td>' +\n",
    "          '<td>Revoke the access token associated with the current user ' +\n",
    "          '    session. After revoking credentials, if you go to the test ' +\n",
    "          '    page, you should see an <code>invalid_grant</code> error.' +\n",
    "          '</td></tr>' +\n",
    "          '<tr><td><a href=\"/clear\">Clear Flask session credentials</a></td>' +\n",
    "          '<td>Clear the access token currently stored in the user session. ' +\n",
    "          '    After clearing the token, if you <a href=\"/test\">test the ' +\n",
    "          '    API request</a> again, you should go back to the auth flow.' +\n",
    "          '</td></tr></table>')\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "  # When running locally, disable OAuthlib's HTTPs verification.\n",
    "  # ACTION ITEM for developers:\n",
    "  #     When running in production *do not* leave this option enabled.\n",
    "  os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'\n",
    "\n",
    "  # Specify a hostname and port that are set as a valid redirect URI\n",
    "  # for your API project in the Google API Console.\n",
    "  app.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1"
  },
  "kernelspec": {
   "display_name": "Python 3.9.7 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
